name = "cf-workers-audit-logs"
workers_dev = true
type = "javascript"
main = "index.js"
compatibility_date = "2023-07-10"

[triggers]
crons = ["* * * * *"]

# uncomment if you are deploying manually
# kv_namespaces = [{binding="KV_AUDIT_LOGS", id="your_kv_namespace_id"}]
